site_name: Dev Notes LR
site_description: Repositorio personal de notas t√©cnicas, roadmaps y aprendizaje continuo.
site_author: L√°zaro
repo_url: https://github.com/lrmilians/dev-notes-lr
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.action.edit
    - search.suggest
    - toc.integrate
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      accent: indigo
  icon:
    logo: material/book
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.tasklist
  - attr_list
  - tables
  - pymdownx.mark
  - pymdownx.arithmatex
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true


nav:
  - üè† Inicio: index.md
  - üß∞ Herramientas:
      - üßë‚Äçüíª Edici√≥n y Control de C√≥digo:
          - VSCode: tools/edition-control-code/vscode.md
          - Git: tools/edition-control-code/git.md
          - GitHub: tools/edition-control-code/github.md
          - GitHub Copilot: tools/edition-control-code/github-copilot.md
          - Gti: tools/edition-control-code/gti.md
      - ‚öô Desarrollo y Automatizaci√≥n:
          - Docker: tools/development-automation/docker.md
          - Kubernetes: tools/development-automation/kubernetes.md
          - Jenkins: tools/development-automation/jenkins.md
          - Terminal: tools/development-automation/terminal.md
      - üìû Comunicaci√≥n y Gesti√≥n:
          - Slack: tools/communication-management/slack.md
          - Linear: tools/communication-management/linear.md
          - Notion: tools/communication-management/notion.md
      - üé® Dise√±o y UX:
          - Figma: tools/ui-ux-design/figma.md
          - Draw.io: tools/ui-ux-design/drawio.md
          - Adobe XD: tools/ui-ux-design/adobe-xd.md
          - Sketch: tools/ui-ux-design/sketch.md
      - üß™ APIs, Testing y Avanzado:
          - Postman: tools/advanced-testing-apis/postman.md
          - IntelliJ IDEA: tools/advanced-testing-apis/intellij.md
          - ChatGPT: tools/advanced-testing-apis/chatgpt.md
      - üåç Comunidad y Aprendizaje:
          - Amigoscode: tools/learning-community/amigoscode.md
          - GitHub Discussions & Dev.to: tools/learning-community/github-discussions-devto.md
  - üíª Lenguajes de Programaci√≥n:
      - PHP: languages/php.md
      - JavaScript: languages/javascript.md
      - Python: languages/python.md
      - C#: languages/csharp.md
      - Java: languages/java.md
      - Rust: languages/rust.md
      - Go: languages/go.md
  - üß© Frameworks:
      - Django: frameworks/django.md
      - Spring Boot: frameworks/springboot.md
      - .NET: frameworks/dotnet.md
      - NestJS: frameworks/nestjs.md
      - Laravel: frameworks/laravel.md
      - Express: frameworks/express.md
      - Symfony: frameworks/symfony.md
  - üóÑ Bases de Datos:
      - SQL:
          - MySQL: data-bases/sql/mysql.md
          - PostgreSQL: data-bases/sql/postgresql.md
      - NoSQL:
          - Firebase: data-bases/nosql/firebase.md
          - MongoDB: data-bases/nosql/mongodb.md
  - üîå APIs y WebServices:
      - Tipos:
          - REST: apis-webservices/types/rest.md
          - SOAP: apis-webservices/types/soap.md
          - gRPC: apis-webservices/types/grpc.md
          - GraphQL: apis-webservices/types/graphql.md
  - ‚òÅ Server y Hosting:
      - Backend Hosting:
          - AWS: server-hosting/backend-hosting/aws.md
          - Azure: server-hosting/backend-hosting/azure.md
          - GCP: server-hosting/backend-hosting/gcp.md
      - Contenerizaci√≥n:
          - Docker: server-hosting/containerization/docker.md
          - KBS: server-hosting/containerization/kbs.md
      - Server:
          - Nginx: server-hosting/server/nginx.md
          - Apache: server-hosting/server/apache.md
  - üèó Patrones de Arquitectura:
      - SOA: architectural-patterns/soa.md
      - Layered: architectural-patterns/layered.md
      - Microservicios: architectural-patterns/microservices.md
      - Event Driven: architectural-patterns/event-driven.md
      - MVC: architectural-patterns/mvc.md
      - Master-Slave: architectural-patterns/master-slave.md
      - Monolito: architectural-patterns/monolith.md
  - üé® Frontend:
      - Frameworks:
          - React: frontend/frameworks/react.md
          - Vue.js: frontend/frameworks/vue.md
          - Angular: frontend/frameworks/angular.md
          - Svelte: frontend/frameworks/svelte.md
      - Estilos:
          - Tailwind CSS: frontend/styles/tailwind.md
          - Bootstrap: frontend/styles/bootstrap.md
      - B√°sicos:
          - JavaScript: frontend/basics/javascript.md
          - HTML5: frontend/basics/html.md
          - CSS: frontend/basics/css.md
  - ‚öô Backend:
      - Lenguajes:
          - Python: backend/languages/python.md
          - Java: backend/languages/java.md
          - C#: backend/languages/csharp.md
          - C++: backend/languages/cpp.md
      - Middleware:
          - RabbitMQ: backend/middleware/rabbitmq.md
          - Elastic: backend/middleware/elastic.md
          - Kafka: backend/middleware/kafka.md
          - Redis: backend/middleware/redis.md
      - Comunicaci√≥n:
          - REST: backend/communication/rest.md
          - SOAP: backend/communication/soap.md
          - gRPC: backend/communication/grpc.md
          - GraphQL: backend/communication/graphql.md
  - üìö Libros: books/index.md
  - üìö Mkdocs: mkdocs/index.md


